apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      containers:
        - name: cloud-app
          image: mrcrowley21/cloud_app:${IMAGE_VERSION}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 8080
#            initialDelaySeconds: 90
#            periodSeconds: 30
#            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "160m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"