apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-updater-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: actions-runner-system
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io