name: Build and Deploy to Local K8s

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Git commit SHA
        id: new_version
        run: |
          VERSION=$(git rev-parse --short=7 HEAD)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Git commit version: ${VERSION}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build JAR file
        run: ./gradlew build

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mrcrowley21/cloud_app:${{ steps.new_version.outputs.version }}
          no-cache: true

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.2'

      - name: Update deployment
        env:
          IMAGE_VERSION: ${{ steps.new_version.outputs.version }}
        run: |
          sudo apt-get update && sudo apt-get install -y gettext-base
          envsubst < deployment.yaml | kubectl apply -f - -n default
          kubectl rollout status deployment/cloud-app -n default