name: Rollback Deployment

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.2'

      - name: Rollback deployment
        run: |
          echo "Rolling back to the previous deployment..."
          kubectl rollout undo deployment/cloud-app -n default
