name: Rollback Deployment

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Rollback deployment
        run: |
          echo "Rolling back to the previous deployment..."
          kubectl rollout undo deployment/cloud-app -n default
